services:
  machine1:
    image: debug_image 
    entrypoint : gdb ./build/test/connect
    tty: true
    stdin_open: true
    networks:
       crypto-network:
          ipv4_address: 122.0.0.3

  machine2:
    image: debug_image
    entrypoint : gdb ./build/test/listen
    tty: true
    stdin_open: true
    networks:
       crypto-network:
          ipv4_address: 122.0.0.4

networks:
  crypto-network:
      ipam:
        driver: default 
        config: 
          - subnet: "122.0.0.0/24"
